// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVpzeloe42hHYKRhHTbq23DZ9Nd0NYuag',
    appId: '1:687970650435:web:412a61a071c7a37c6807f6',
    messagingSenderId: '687970650435',
    projectId: 'kiddoai-690ac',
    authDomain: 'kiddoai-690ac.firebaseapp.com',
    storageBucket: 'kiddoai-690ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqlbYzjEFjM-03aiqyIh5bJryhXZfEEM',
    appId: '1:687970650435:android:4ee64ab71195dcac6807f6',
    messagingSenderId: '687970650435',
    projectId: 'kiddoai-690ac',
    storageBucket: 'kiddoai-690ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwFbcLX4LTikRIM9LulYgRaLMjigFgus',
    appId: '1:687970650435:ios:02ca1667fc4812f16807f6',
    messagingSenderId: '687970650435',
    projectId: 'kiddoai-690ac',
    storageBucket: 'kiddoai-690ac.firebasestorage.app',
    iosClientId: '687970650435-tsbmg96meugving4ocpanotdekekl3kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiddoai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwFbcLX4LTikRIM9LulYgRaLMjigFgus',
    appId: '1:687970650435:ios:02ca1667fc4812f16807f6',
    messagingSenderId: '687970650435',
    projectId: 'kiddoai-690ac',
    storageBucket: 'kiddoai-690ac.firebasestorage.app',
    iosClientId: '687970650435-tsbmg96meugving4ocpanotdekekl3kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiddoai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVpzeloe42hHYKRhHTbq23DZ9Nd0NYuag',
    appId: '1:687970650435:web:cf75558f95fcf9736807f6',
    messagingSenderId: '687970650435',
    projectId: 'kiddoai-690ac',
    authDomain: 'kiddoai-690ac.firebaseapp.com',
    storageBucket: 'kiddoai-690ac.firebasestorage.app',
  );
}
